### PR TITLE
Implement first three models

### LINKED ISSUE #46: Authorization tables
This is the highest priority for setting up database stuff.

Estimated Time: 45m
Actual: 60m

### LINKED ISSUE #48: Create the DB REPL for Richard
Describe the task in this section.

Estimated Time: 30m
Actual: 40m

### PR DESCRIPTION
**Pull request by CodeTriangle**
I have done this all so that I can support the UserAccount model, which depends on two other models to work. I also got some good practice with primary keys.

### CODE REVIEW

**Comment by CodeTriangle** [comment]
This should implement everything I wanted for #46.

**Comment by Kytech** [comment]
This looks good to me. I'll approve this to have you pull it into master after you update the time spent on the related issue. One note, I did have to make a slight change to where relations were defined. They were defined properly, though it looks like the generated models actually create a specific function for registering relations, so things should be put there. You can look at the change I made when writing the REPL. It wouldn't work until I made that adjustment.

**Review by Kytech — APPROVED** [review]

**Comment by CodeTriangle** [comment]
> This looks good to me. I'll approve this to have you pull it into master after you update the time spent on the related issue.

Done.

> One note, I did have to make a slight change to where relations were defined. They were defined properly, though it looks like the generated models actually create a specific function for registering relations, so things should be put there. You can look at the change I made when writing the REPL. It wouldn't work until I made that adjustment.

I was not sure at all how well this would work; it was just some random guy's SO answer. I'm glad you found a way to make it function properly. The documentation for associations is not great.

**Comment by CodeTriangle** [comment]
Oh, and I believe that this should also close #48. @Kytech add the time estimate for that before merging this.

**Pull request merged**
